[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
optimizer = true
optimizer_runs = 200

ffi=true
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]